services:
  - type: redis
    name: idempotency-redis
    plan: free
    region: frankfurt

    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow connections

  - type: web
    name: idempotency-gateway
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: REDIS_HOST
        fromService:
          type: redis
          name: idempotency-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: idempotency-redis
          property: port
